# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-qrm4j-w_fdd3OzI-xysWpWDkws0u-M
"""

# ============================================
# 🐾 台灣動物收容所分析
# Taiwan Animal Shelter & Adoption Analysis
# ============================================
# Author: Tamara
# Date: May 2026
# Main Question: Are abandoned pets in
# Kaohsiung getting enough support?
#
# Datasets:
# 1. Live API: 動物認領養 (Daily updates)
# 2. Static: 高雄市動物醫院一覽表 (Vet clinics)
# 3. Population: SEGIS 高雄市各區人口統計
# 4. Geographic: Taiwan District Boundaries
#
# Tools: Python, Pandas, Matplotlib,
# Seaborn, Scipy, Folium, GeoPandas
# ============================================

#installation
#! pip install folium geopandas -q

#libraries inspection
#! pip show requests
#! pip show matplotlib
#! pip show seaborn
#!pip install Pillow

#1. Imports

import requests
import pandas as pd
from datetime import datetime, date
import matplotlib.pyplot as plt
from io import BytesIO
import seaborn as sns
from scipy import stats
import geopandas as gpd
import folium
from PIL import Image

#2. Fetch&Load Data

#Live dataset: URL/request/open/store/convert
URL_adp = "https://data.moa.gov.tw/Service/OpenData/TransService.aspx?UnitId=QcbUEzN6E6DL&IsTransData=1"
live_dataset_adp = requests.get(URL_adp)
store_adp = live_dataset_adp.json()
df_adp = pd.DataFrame(store_adp)
df_adp.to_csv(f"live_data_AnimalAdoption_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv", encoding = 'utf-8-sig')

#Static dataset: load to GoogleDrive/pd.read
df_vet = pd.read_csv("https://drive.google.com/uc?id=14cAoE2ezQ8pw2GlG0zgO99oM-C_02QqS")

#Static snapshot
df_adp_old = pd.read_csv("https://drive.google.com/uc?id=10pfR385BujrglMc94CQEb9z-ED26H7xK")

#Population district
URL_pop = "https://segisws.moi.gov.tw/STATWSSTData/OpenService.asmx/GetAdminSTDataForOpenCode?oCode=BF3B727F423963563B5AF84EB798086251A1FBEE829C41DBF0767011744D917A2539094FCB65D41BDDE79C332EB9258D"
population_dataset = requests.get(URL_pop)
store_pop = population_dataset.json()
df_population_district = pd.DataFrame(store_pop['RowDataList'])
df_population_district.to_csv(f"Kaohsiung Population_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv", encoding = 'utf-8-sig')

# Taiwan official district boundaries (village level, will dissolve to district)
geo_url = "https://raw.githubusercontent.com/ronnywang/twgeojson/master/twvillage2010.json"
gdf = gpd.read_file(geo_url)
gdf_kaohsiung = gdf[gdf['county'] == '高雄市']

#3. Clean&Calculate

#Date calculation
df_adp['city_filter'] = df_adp['animal_place'].str[:3]
df_adp['animal_opendate'] = pd.to_datetime(df_adp['animal_opendate'])
df_adp['days_waiting']= (pd.Timestamp.now()-df_adp['animal_opendate']).dt.days.astype('Int64')

#Clean wrong input for days waiting
df_adp_clean = df_adp[df_adp['days_waiting']>=0]
min_check = df_adp_clean['days_waiting'].min()

#Add city filter
df_kaohsiung = df_adp_clean[df_adp_clean['animal_place'].str.contains('高雄')]
df_taipei = df_adp_clean[df_adp_clean['animal_place'].str.contains('臺北')]
df_newtaipei = df_adp_clean[df_adp_clean['animal_place'].str.contains('新北')]
df_taichung = df_adp_clean[df_adp_clean['animal_place'].str.contains('臺中')]
df_tainan = df_adp_clean[df_adp_clean['animal_place'].str.contains('臺南')]

# Old snapshot
df_adp_old['city_filter'] = df_adp_old['animal_place'].str[:3]
df_kaohsiung_old = df_adp_old[df_adp_old['animal_place'].str.contains('高雄')]

#Add Kaohsiung city filter
df_kh_population = df_population_district[df_population_district['COUNTY'].str.contains('高雄')]
#Vets per district
df_vet_count = df_vet['行政區'].value_counts().reset_index()
#Merge Kaoh population & vet count
df_district = pd.merge(df_kh_population, df_vet_count, left_on='TOWN', right_on='行政區', how='left')
#print(df_district.head())

#NaN values to 0
df_district['count'] = df_district['count'].fillna(0)

#Add a new column: Vets per 100k population
df_district['vets_per_100k'] = (df_district['count'] / df_district['P_CNT']) * 100000
#print(df_district[['TOWN', 'count', 'P_CNT', 'vets_per_100k']].head(10))

# Remove sea zones
gdf_kaohsiung = gdf_kaohsiung[~gdf_kaohsiung['town'].str.contains('海')]
# Dissolve villages into districts
gdf_districts = gdf_kaohsiung.dissolve(by='town').reset_index()
#print(gdf_districts[['town', 'geometry']].head())
#print(f"Total districts: {len(gdf_districts)}")

gdf_final = gdf_districts.merge(df_district, left_on='town', right_on='TOWN', how='left')
#print(gdf_final[['town', 'count', 'vets_per_100k']].head())

#print(gdf_final[gdf_final['vets_per_100k'] == 0][['town', 'P_CNT']])

#4. Analysis

#Waiting days mean calculation
df_kaohsiung_mean = df_kaohsiung['days_waiting'].mean()
df_taipei_mean = df_taipei['days_waiting'].mean()
df_newtaipei_mean = df_newtaipei['days_waiting'].mean()
 #National waiting days mean calculation
national_mean = df_adp_clean['days_waiting'].mean()

#BIG - Animal variaty
df_kaohsiung[df_kaohsiung['animal_bodytype'] == 'BIG']['animal_Variety'].value_counts()

#ANOVA Stat:
big = df_kaohsiung[df_kaohsiung['animal_bodytype'] == 'BIG']['days_waiting']
medium = df_kaohsiung[df_kaohsiung['animal_bodytype'] == 'MEDIUM']['days_waiting']
small = df_kaohsiung[df_kaohsiung['animal_bodytype'] == 'SMALL']['days_waiting']
stats.f_oneway(big, medium, small)
#P value of 0.6246 is greater than 0.05, so:
#"The difference in waiting time between BIG, MEDIUM, and SMALL animals
#is NOT statistically significant — it could just be coincidence!"

#City comparison analysis:
df_adp_clean['city_filter'].value_counts()
population_data = {
    'City': ['Kaohsiung', 'Taipei', 'New Taipei', 'Taichung', 'Tainan'],
    'Population': [2731412, 2490869, 4047001, 2860601, 1858651],
    'Animals': [df_kaohsiung.shape[0], df_taipei.shape[0], df_newtaipei.shape[0], df_taichung.shape[0], df_tainan.shape[0]]
}
df_population = pd.DataFrame(population_data)
df_population['animals_per_100k'] = (df_population['Animals'] / df_population['Population']) * 100000
 #National animals vs population
national_pop_mean = df_population['animals_per_100k'].mean()

#Adoption Tracker
# Adopted:
old_ids = set(df_kaohsiung_old['animal_id'])
new_ids = set(df_kaohsiung['animal_id'])
adopted = old_ids - new_ids
# New at shelter
new_inshelter = new_ids - old_ids
df_adopted = df_kaohsiung_old[df_kaohsiung_old['animal_id'].isin(adopted)]
df_new_arrival = df_kaohsiung[df_kaohsiung['animal_id'].isin(new_inshelter)]

#5. Charts

#Waiting days bar comparison:
xaxis = ['Kaohsiung', 'Taipei', 'New Taipei']
yaxis = [df_kaohsiung_mean, df_taipei_mean, df_newtaipei_mean]
plt.bar(xaxis, yaxis, color=['green', 'orange', 'red'])
plt.title("Waiting Days Bar Comparison")
plt.ylabel("Days")
plt.axhline(y=national_mean, color='black', linestyle='--', label='National Average')
plt.legend()
plt.show()

#Iceberg bar chart:
xaxis = ['In Shelter\n(API Data)', 'Shelter Capacity\n(News Source*)', 'Strays\n(Govt Estimate*)']
yaxis = [df_kaohsiung.shape[0], 900, 10000]
plt.bar(xaxis, yaxis, color=['green', 'orange', 'red'])
plt.ylabel("Quantity")
plt.title("Kaohsiung Shelter Capacity vs Street Animals\n*External sources: news articles & government estimates")
plt.show()

#Animal size Vs Days Waiting boxplot:
sns.boxplot(data=df_kaohsiung, x='animal_bodytype', y='days_waiting')
plt.title("Size vs Waiting")
plt.show()

#Animals per city population
plt.bar(df_population['City'], df_population['animals_per_100k'], color=['green', 'orange', 'yellow', 'blue','red'])
plt.title("Animals per city population")
plt.ylabel("Animals per 100k")
plt.axhline(y=national_pop_mean, color='black', linestyle='--', label='National Average')
plt.legend()
plt.show()

# Round vets_per_100k to 2 decimal places
gdf_final['vets_per_100k'] = gdf_final['vets_per_100k'].round(2)

# Create base map centered on Kaohsiung
m = folium.Map(location=[22.6273, 120.3014], zoom_start=10)

# Add choropleth layer
folium.Choropleth(
    geo_data=gdf_final,
    data=gdf_final,
    columns=['town', 'vets_per_100k'],
    key_on='feature.properties.town',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.5,
    legend_name='Vets per 100k Population'
).add_to(m)

# Add tooltips
folium.GeoJson(
    gdf_final,
    style_function=lambda x: {'fillOpacity': 0, 'weight': 0},
    tooltip=folium.GeoJsonTooltip(
        fields=['town', 'vets_per_100k', 'count'],
        aliases=['District:', 'Vets per 100k:', 'Total Vets:'],
    )
).add_to(m)

# Save map
m.save('kaohsiung_vet_map.html')
print("Map saved!")
m #display inline

#Animal Tracker
snapshot_date = date(2026, 4, 23)
today = date.today()
days_tracked = (today - snapshot_date).days
print(f"📊 Kaohsiung Adoption Tracker")
print(f"Snapshot date: April 23rd 2026")
print(f"Days tracked: {days_tracked}")
print(f"Animals that found homes: {len(adopted)} 🐾")
print(f"Average: {round(len(adopted)/days_tracked, 1)} animals per day! 🏠")
print(f"New animals needing homes: {len(new_inshelter)} 🆕")
print(f"  - Dogs: {df_new_arrival['animal_kind'].value_counts().get('狗', 0)} 🐕")
print(f"  - Cats: {df_new_arrival['animal_kind'].value_counts().get('貓', 0)} 🐱")

#8. Hall of Forgotten Friends

df_top_dogs = df_kaohsiung[(df_kaohsiung['animal_kind'] == '狗') & (df_kaohsiung['album_file'] != '')].sort_values('days_waiting', ascending=False).head(3)
df_top_cats = df_kaohsiung[(df_kaohsiung['animal_kind'] == '貓') & (df_kaohsiung['album_file'] != '')].sort_values('days_waiting', ascending=False).head(1)
df_forgotten = pd.concat([df_top_dogs, df_top_cats])

for _, row in df_forgotten.iterrows():
    print(f"🐾 Animal ID: {row['animal_id']}")
    print(f"⏰ Waiting: {row['days_waiting']} days ({round(row['days_waiting']/365, 1)} years)")
    print(f"🐕 Breed: {row['animal_Variety']} | Size: {row['animal_bodytype']} | Age: {row['animal_age']}")
    if row['album_file']:
        try:
            response = requests.get(row['album_file'], timeout=10)
            img = Image.open(BytesIO(response.content))
            plt.figure(figsize=(4, 3))
            plt.imshow(img)
            plt.axis('off')
            plt.title(f"ID: {row['animal_id']} | {row['days_waiting']} days waiting", fontsize=10)
            plt.tight_layout()
            plt.show()
        except Exception as e:
            print(f"📷 Photo unavailable: {e}")
    print("---")